### ISSUE TITLE
Git error when using as app inside monorepo

### ISSUE THREAD

**Issue by vbnetadmin** [shuding/nextra#1226]
I'm using nextra docs theme inside my monorepo

Structure:

apps
... docs
... web
packages
... 

When using turbo to run dev server, I get git error from nextra:

```
tpl_app  | docs:dev: [nextra] Init git repository failed Error: Discover git repo from [/app/apps/docs] failed: could not find repository from '/app/apps/docs'; class=Repository (6); code=NotFound (-3)
tpl_app  | docs:dev:     at file:///app/node_modules/.pnpm/nextra@2.1.0_q76c2b4vyoegvsbrcwkfvimnai/node_modules/nextra/dist/loader.mjs:249:37
tpl_app  | docs:dev:     at Generator.next (<anonymous>)
tpl_app  | docs:dev:     at fulfilled (file:///app/node_modules/.pnpm/nextra@2.1.0_q76c2b4vyoegvsbrcwkfvimnai/node_modules/nextra/dist/chunk-HIDP27A7.mjs:36:24) {
tpl_app  | docs:dev:   code: 'GenericFailure'
tpl_app  | docs:dev: }
```

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/110173629/211641607-2f3f4ca2-9803-464c-9d09-3b434655ef9b.png">

Looks like nextra is trying to look for .git folder inside apps/docs/ directory, but as it is monorepo, git directory is located in upper level.

This isn't fatal error, but I would appreciate feedback, how to eliminate this error

Example for reproduction:

https://github.com/wayofdev/next-starter-tpl/tree/feat/docs

**Comment by pplonski** [comment]
I got the similar issue in directory that is not tracked by git.

**Comment by lotyp** [comment]
Probably happens here, in loader file:

https://github.com/shuding/nextra/blob/73241b3fee58f0318e9349a5eb7650a7cd55a4e3/packages/nextra/src/loader.ts#L53

**Comment by wottpal** [comment]
Getting the same error, but only during CI when deploying to Vercel. Not when building the project locally.

I'm not using a monorepo. But it might be related to `pnpm` as I see we're both using it. 🤔

```
[nextra] Init git repository failed Error: Discover git repo from [/vercel/path0] failed: could not find repository from '/vercel/path0'; class=Repository (6); code=NotFound (-3)
07:18:32.314 | at file:///vercel/path0/node_modules/.pnpm/nextra@2.2.14_3vryta7zmbcsw4rrqf4axjqggm/node_modules/nextra/dist/loader.mjs:21:37 {
07:18:32.314 | code: 'GenericFailure'
07:18:32.314 | }
07:18:42.520
```

**Comment by FACOLOMBANI** [comment]
Any news about this? Have same issue inside monorepo.
