### ISSUE TITLE
Warning: Invalid DOM property `stop-color`. Did you mean `stopColor`?

### ISSUE THREAD

**Issue by alex-flea** [shuding/nextra#1352]
v2.2.10

```
[nextra] Error validating the theme config
[nextra] Error in config ``: invalid theme config
Warning: Invalid DOM property `stop-color`. Did you mean `stopColor`?
    at stop
    at linearGradient
    at defs
    at svg
    at a
    at eval (webpack-internal:///./node_modules/nextra-theme-docs/dist/index.js:237:18)
    at nav
    at div
    at Navbar (webpack-internal:///./node_modules/nextra-theme-docs/dist/index.js:1753:19)
    at div
    at InnerLayout (webpack-internal:///./node_modules/nextra-theme-docs/dist/index.js:3221:3)
    ...
```

**Comment by B2o5T** [comment]
I don't have this warning, can you help me find a place where `stop-color` attribute occurs in your stacktrace?

**Comment by B2o5T** [comment]
can you show your `logo` property in the theme config? I think it's on your side

**Comment by B2o5T** [comment]
Ok, closing it, in the latest version you should have better errors
