### ISSUE TITLE
Deleted page appear on search

### ISSUE THREAD

**Issue by happyuniv** [shuding/nextra#1439]
i start by cloning nextra-docs-template and created mdx file on page folder and deleted.
but it still appear on search and when i click this deleted one, it routes to 404 page.
also when i type a word on search, there's error message on console :

next-dev.js?7e00:20 Warning: React has detected a change in the order of Hooks called by Search. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useState                   useState
2. useContext                 useContext
3. useState                   useState
4. useContext                 useContext
5. useContext                 useContext
6. useRef                     useRef
7. useRef                     useRef
8. useEffect                  useEffect
9. useEffect                  useEffect
10. useEffect                 useEffect
11. useCallback               useCallback
12. useState                  useState
13. useEffect                 useEffect
14. useCallback               useCallback
15. useContext                useContext
16. undefined                 useContext
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    at Search (webpack-internal:///./node_modules/.pnpm/nextra-theme-docs@2.0.1_6jx7hpii6hgsrmhxgqrmo3277u/node_modules/nextra-theme-docs/dist/index.js:1116:3)
    at Flexsearch (webpack-internal:///./node_modules/.pnpm/nextra-theme-docs@2.0.1_6jx7hpii6hgsrmhxgqrmo3277u/node_modules/nextra-theme-docs/dist/index.js:1416:3)
    at component (webpack-internal:///./node_modules/.pnpm/nextra-theme-docs@2.0.1_6jx7hpii6hgsrmhxgqrmo3277u/node_modules/nextra-theme-docs/dist/index.js:2561:17)
    at nav
    at div
    at Navbar (webpack-internal:///./node_modules/.pnpm/nextra-theme-docs@2.0.1_6jx7hpii6hgsrmhxgqrmo3277u/node_modules/nextra-theme-docs/dist/index.js:1832:19)
    at div
    at InnerLayout (webpack-internal:///./node_modules/.pnpm/nextra-theme-docs@2.0.1_6jx7hpii6hgsrmhxgqrmo3277u/node_modules/nextra-theme-docs/dist/index.js:3093:3)
    at f (webpack-internal:///./node_modules/.pnpm/next-themes@0.2.1_6jx7hpii6hgsrmhxgqrmo3277u/node_modules/next-themes/dist/index.module.js:8:597)
    at $ (webpack-internal:///./node_modules/.pnpm/next-themes@0.2.1_6jx7hpii6hgsrmhxgqrmo3277u/node_modules/next-themes/dist/index.module.js:8:348)
    at ConfigProvider (webpack-internal:///./node_modules/.pnpm/nextra-theme-docs@2.0.1_6jx7hpii6hgsrmhxgqrmo3277u/node_modules/nextra-theme-docs/dist/index.js:154:3)
    at Layout (webpack-internal:///./node_modules/.pnpm/nextra-theme-docs@2.0.1_6jx7hpii6hgsrmhxgqrmo3277u/node_modules/nextra-theme-docs/dist/index.js:3168:75)
    at App (webpack-internal:///./node_modules/.pnpm/next@13.0.6_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/pages/_app.js:27:1)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/.pnpm/next@13.0.6_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/shared/lib/router/adapters.js:62:11)
    at ErrorBoundary (webpack-internal:///./node_modules/.pnpm/next@13.0.6_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:301:63)
    at ReactDevOverlay (webpack-internal:///./node_modules/.pnpm/next@13.0.6_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:850:919)
    at Container (webpack-internal:///./node_modules/.pnpm/next@13.0.6_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/index.js:60:1)
    at AppContainer (webpack-internal:///./node_modules/.pnpm/next@13.0.6_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/index.js:173:11)
    at Root (webpack-internal:///./node_modules/.pnpm/next@13.0.6_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/index.js:346:11)
window.console.error @ next-dev.js?7e00:20

**Comment by shuding** [comment]
It seems that you are using `nextra-theme-docs@2.0.1`. This bug was fixed in latest version already.
