### ISSUE TITLE
Broken build on Vercel

### ISSUE THREAD

**Issue by The-Code-Monkey** [shuding/nextra#1571]
```
[nextra] Error compiling /vercel/path0/pages/contact-us.mdx.
07:57:42.743 | [nextra] Error compiling /vercel/path0/pages/gallery.mdx.
07:57:42.743 | [nextra] Error compiling /vercel/path0/pages/index.mdx.
07:57:42.743 | [nextra] Error compiling /vercel/path0/pages/help-guides.mdx.
07:57:42.743 | [nextra] Error compiling /vercel/path0/pages/help-guides/how-to-build-a-wildlife-pond.mdx.
07:57:42.743 | [nextra] Error compiling /vercel/path0/pages/help-guides/how-to-choose-the-best-pond-filter-and-uv-for-your-pond.mdx.
07:57:42.743 | [nextra] Error compiling /vercel/path0/pages/help-guides/looking-after-a-pond-in-winter.mdx.
07:57:42.743 | [nextra] Error compiling /vercel/path0/pages/services/fish-health.mdx.
07:57:42.743 | [nextra] Error compiling /vercel/path0/pages/services/liner-and-fiberglass-installation.mdx.
07:57:42.744 | [nextra] Error compiling /vercel/path0/pages/services/pond-cleaning-and-maintain.mdx.
07:57:42.744 | [nextra] Error compiling /vercel/path0/pages/services/pond-design-and-construction.mdx.
07:57:42.744 | [nextra] Error compiling /vercel/path0/pages/services/pond-pump-filter-and-equipment-installation.mdx.
07:57:44.447 | Failed to compile.
07:57:44.447 |  
07:57:44.448 | ./pages/contact-us.mdx
07:57:44.448 | TypeError: String(...).replaceAll is not a function
07:57:44.448 | at compileMdx (file:///vercel/path0/node_modules/nextra/dist/compile.mjs:318:29)
07:57:44.448 | at async loader (file:///vercel/path0/node_modules/nextra/dist/loader.mjs:109:7)
07:57:44.448 |  
07:57:44.448 | ./pages/gallery.mdx
07:57:44.448 | TypeError: String(...).replaceAll is not a function
07:57:44.449 | at compileMdx (file:///vercel/path0/node_modules/nextra/dist/compile.mjs:318:29)
07:57:44.449 | at async loader (file:///vercel/path0/node_modules/nextra/dist/loader.mjs:109:7)
07:57:44.449 |  
07:57:44.449 | ./pages/help-guides.mdx
07:57:44.449 | TypeError: String(...).replaceAll is not a function
07:57:44.449 | at compileMdx (file:///vercel/path0/node_modules/nextra/dist/compile.mjs:318:29)
07:57:44.449 | at async loader (file:///vercel/path0/node_modules/nextra/dist/loader.mjs:109:7)
07:57:44.449 |  
07:57:44.450 | ./pages/help-guides/how-to-build-a-wildlife-pond.mdx
07:57:44.450 | TypeError: String(...).replaceAll is not a function
07:57:44.450 | at compileMdx (file:///vercel/path0/node_modules/nextra/dist/compile.mjs:318:29)
07:57:44.450 | at async loader (file:///vercel/path0/node_modules/nextra/dist/loader.mjs:109:7)
07:57:44.450 |  
07:57:44.450 | ./pages/help-guides/how-to-choose-the-best-pond-filter-and-uv-for-your-pond.mdx
07:57:44.450 | TypeError: String(...).replaceAll is not a function
07:57:44.451 | at compileMdx (file:///vercel/path0/node_modules/nextra/dist/compile.mjs:318:29)
07:57:44.451 | at async loader (file:///vercel/path0/node_modules/nextra/dist/loader.mjs:109:7)
07:57:44.451 |  
07:57:44.451 |  
07:57:44.451 | > Build failed because of webpack errors
07:57:44.478 | error Command failed with exit code 1.
07:57:44.478 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
07:57:44.496 | Error: Command "yarn build" exited with 1
07:57:44.567
```

This is the error i get which is coming from within the nextra package, I do have a fully custom theme built on top of the nextra logic, but i wouldn't have thought that would cause the issue.

**Comment by The-Code-Monkey** [comment]
The stranger thing is it builds locally using the next build command. It only breaks when running the command on a server.

**Comment by B2o5T** [comment]
which node version do you use in Vercel?

**Comment by The-Code-Monkey** [comment]
I'm currently using 14?

**Comment by B2o5T** [comment]
If you set `16` the error should be gone

**Comment by The-Code-Monkey** [comment]
cheers that worked, might want to add a warning or something if the node version is less than 16
