### ISSUE TITLE
Build fails with react error when updating from 2.2.15 to 2.2.16

### ISSUE THREAD

**Issue by danez** [shuding/nextra#1602]
My builds started failing when I (well renovate-bot) update nextra to 2.2.16. 

For every single page I get this error during the first build
```
$ pnpm build
9:53:50 AM: > @react-docgen-internal/website@0.0.0 build /opt/build/repo/packages/website
9:53:50 AM: > next build
9:53:50 AM: info  - Linting and checking validity of types...
9:53:52 AM: info  - Creating an optimized production build...
9:53:58 AM: [nextra] Didn't find "_app.mdx" file, created it for you for better performance.
info  - Compiled successfully
9:53:58 AM: info  - Collecting page data...
9:54:06 AM: info  - Generating static pages (0/11)
9:54:06 AM: info  - Generating static pages (2/11)
9:54:06 AM: Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
9:54:06 AM:     at Zc (/opt/build/repo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:493)
9:54:06 AM:     at Z (/opt/build/repo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
9:54:06 AM:     at Zc (/opt/build/repo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
9:54:06 AM:     at Z (/opt/build/repo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
9:54:06 AM:     at Xc (/opt/build/repo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:409)
9:54:06 AM:     at Zc (/opt/build/repo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:210)
9:54:06 AM:     at Z (/opt/build/repo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
9:54:06 AM:     at Zc (/opt/build/repo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
9:54:06 AM:     at Z (/opt/build/repo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
9:54:06 AM:     at $c (/opt/build/repo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
9:54:06 AM: Error occurred prerendering page "/docs/getting-started". Read more: https://nextjs.org/docs/messages/prerender-error
```

The second build (with `_app.mdx` present) does work, but because the `_app.mdx` wasn't committed every automated build was failing like this for me. Only after I committed the file it stopped happening.

Maybe this can be improved, so that it works already for the build that creates the `_app.mdx`? Maybe it is created to late and is not considered for the first build?

Here is the repo: https://github.com/reactjs/react-docgen/tree/main/packages/website/

**Comment by B2o5T** [comment]
Strange because `_app.mdx` created synchronously with `writeFileSync`. https://github.com/shuding/nextra/blob/d4b1dbd595aa0e1bab1210fd0cf1422b60704730/packages/nextra/src/loader.ts#L39

Maybe we should disable auto creation `_app.mdx`?
