### ISSUE TITLE
Nextra-docs-template running error

### ISSUE THREAD

**Issue by zhgh** [shuding/nextra#1682]
# I got an error when i run the nextra-docs-template project.

## it look like something wrong with the nextra loader

index.js?ee58:594 Uncaught ModuleBuildError: Module build failed (from ./node_modules/.pnpm/registry.npmmirror.com+nextra@2.2.20_bhgafntz2ozm43l35i5qtimxry/node_modules/nextra/loader.js):
TypeError: String(...).replaceAll is not a function
    at compileMdx (file:///E:/testwork/nextra-docs-template/node_modules/.pnpm/registry.npmmirror.com+nextra@2.2.20_bhgafntz2ozm43l35i5qtimxry/node_modules/nextra/dist/compile.mjs:332:29)
    at async loader (file:///E:/testwork/nextra-docs-template/node_modules/.pnpm/registry.npmmirror.com+nextra@2.2.20_bhgafntz2ozm43l35i5qtimxry/node_modules/nextra/dist/loader.mjs:117:7)
    at compileMdx (file:///E:/testwork/nextra-docs-template/node_modules/.pnpm/registry.npmmirror.com+nextra@2.2.20_bhgafntz2ozm43l35i5qtimxry/node_modules/nextra/dist/compile.mjs:332:29)
    at async loader (file:///E:/testwork/nextra-docs-template/node_modules/.pnpm/registry.npmmirror.com+nextra@2.2.20_bhgafntz2ozm43l35i5qtimxry/node_modules/nextra/dist/loader.mjs:117:7)
    at processResult (file://E:\testwork\nextra-docs-template\node_modules\.pnpm\registry.npmmirror.com+next@12.3.4_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\compiled\webpack\bundle5.js:28:394802)
    at <unknown> (file://E:\testwork\nextra-docs-template\node_modules\.pnpm\registry.npmmirror.com+next@12.3.4_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\compiled\webpack\bundle5.js:28:396519)
    at <unknown> (file://E:\testwork\nextra-docs-template\node_modules\.pnpm\registry.npmmirror.com+next@12.3.4_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\compiled\webpack\bundle5.js:1:270935)
    at <unknown> (file://E:\testwork\nextra-docs-template\node_modules\.pnpm\registry.npmmirror.com+next@12.3.4_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\compiled\webpack\bundle5.js:1:268091)
    at E.callback (file://E:\testwork\nextra-docs-template\node_modules\.pnpm\registry.npmmirror.com+next@12.3.4_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\compiled\webpack\bundle5.js:1:266340)
    at <unknown> (file:///E:/testwork/nextra-docs-template/node_modules/.pnpm/registry.npmmirror.com+nextra@2.2.20_bhgafntz2ozm43l35i5qtimxry/node_modules/nextra/dist/loader.mjs:238:80)
getServerError @ client.js?a5ae:7
eval @ index.js?ee58:594
setTimeout (async)
eval @ index.js?ee58:582
step @ tslib.es6.js?15be:102
eval @ tslib.es6.js?15be:83
asyncGeneratorStep @ _async_to_generator.js?cba7:23
_next @ _async_to_generator.js?cba7:12
Promise.then (async)
asyncGeneratorStep @ _async_to_generator.js?cba7:32
_next @ _async_to_generator.js?cba7:12
eval @ _async_to_generator.js?cba7:17
eval @ _async_to_generator.js?cba7:9
_hydrate @ index.js?ee58:637
hydrate @ index.js?ee58:527
eval @ next-dev.js?5d16:40
Promise.then (async)
eval @ next-dev.js?5d16:35
./node_modules/.pnpm/registry.npmmirror.com+next@12.3.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/next-dev.js @ main.js?ts=1679905717244:555
options.factory @ webpack.js?ts=1679905717244:649
__webpack_require__ @ webpack.js?ts=1679905717244:37
__webpack_exec__ @ main.js?ts=1679905717244:1240
(anonymous) @ main.js?ts=1679905717244:1241
webpackJsonpCallback @ webpack.js?ts=1679905717244:1197
(anonymous) @ main.js?ts=1679905717244:9
next-dev.js?5d16:20 ./pages/index.mdx
TypeError: String(...).replaceAll is not a function

**Comment by zhgh** [comment]
Just update the node.js version
