### ISSUE TITLE
Uncaught Error: Minified React error #425

### ISSUE THREAD

**Issue by Noah-Haf** [shuding/nextra#1786]
Whenever I visit [my site ](https://docs.rankgun.works/) I always get this error inside of console. I have no idea what this could be causing this issue. 

```
framework-2c79e2a64abdb08b.js:1  Uncaught Error: Minified React error #425; visit https://reactjs.org/docs/error-decoder.html?invariant=425 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at rh (framework-2c79e2a64abdb08b.js:1:40262)
    at framework-2c79e2a64abdb08b.js:1:103566
    at oD (framework-2c79e2a64abdb08b.js:1:106316)
    at oO (framework-2c79e2a64abdb08b.js:1:99264)
    at framework-2c79e2a64abdb08b.js:1:99071
    at oF (framework-2c79e2a64abdb08b.js:1:99078)
    at oS (framework-2c79e2a64abdb08b.js:1:94117)
    at x (framework-2c79e2a64abdb08b.js:1:137617)
    at MessagePort.T (framework-2c79e2a64abdb08b.js:1:138147)
framework-2c79e2a64abdb08b.js:1  Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at i (framework-2c79e2a64abdb08b.js:1:120920)
    at oO (framework-2c79e2a64abdb08b.js:1:99204)
    at framework-2c79e2a64abdb08b.js:1:99071
    at oF (framework-2c79e2a64abdb08b.js:1:99078)
    at ox (framework-2c79e2a64abdb08b.js:1:95830)
    at oS (framework-2c79e2a64abdb08b.js:1:94385)
    at x (framework-2c79e2a64abdb08b.js:1:137617)
    at MessagePort.T (framework-2c79e2a64abdb08b.js:1:138147)
```

[My repo](https://github.com/Noah-Haf/RankGunDocs) is public if anybody is curious into looking into my code. Thanks for any help in advance.

**Comment by abhaytalreja** [comment]
I am facing a similar error. Already logged an issue https://github.com/shuding/nextra/issues/1761

**Comment by Noah-Haf** [comment]
Missed this, hopefully this is fixed soon.

**Comment by boostvolt** [comment]
I see you are using Cloudlfare on your website. We had the same problem with ours. Make sure you have unchecked all the boxes under Optimizazion > Auto Minify and then purged the cache. After that everything works for us.

**Comment by Noah-Haf** [comment]
Great suggestion, I used a custom page rule and it has resolved my issue: 

![image](https://user-images.githubusercontent.com/61884850/234078847-6ab5aba0-0f03-4bf4-9147-da2416f8a925.png)
