### ISSUE TITLE
_meta.json doesn't working in blog theme

### ISSUE THREAD

**Issue by ulf-frostypaw** [shuding/nextra#1801]
I have tried to create a project similar to the Demo, but _meta.json does not rearrange the order of the pages in the indicated
```json
{
    "index": "Home",
    "posts" : "Blog",
    "about": "About Us"
}
```
...
Or is there no support for this template?

**Comment by BarakBarz** [comment]
I also experience issues with this!

**Comment by brooksdra** [comment]
I started a brand new Nextra site, and added a new page levelup.mdx (title: LevelUp) to pages directory and the menu sorted LevelUp About Photos Posts. 

I added a _meta.json with the following:

```
{
  "index": "About",
  "levelup": "LevelUp",
  "photos": "Photos",
  "posts": {
    "title": "Posts"
  }
}
```
Note: I tried several variations of _meta.json.

I get the following error when Vercel attempts to deploy...

```
[10:26:58.727] Error occurred prerendering page "/posts". Read more: https://nextjs.org/docs/messages/prerender-error
[10:26:58.728] TypeError: Cannot read properties of undefined (reading 'startsWith')
[10:26:58.728]     at /vercel/path0/.next/server/chunks/242.js:2358:43
[10:26:58.729]     at traverse (/vercel/path0/.next/server/chunks/242.js:2261:9)
[10:26:58.730]     at src_default (/vercel/path0/.next/server/chunks/242.js:2346:5)
[10:26:58.730]     at NextraPage (/vercel/path0/.next/server/pages/posts.js:47:134)
[10:26:58.730]     at d (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
[10:26:58.730]     at bb (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
[10:26:58.730]     at b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
[10:26:58.730]     at b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
[10:26:58.730]     at exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
[10:26:58.730]     at renderDocument (/vercel/path0/node_modules/next/dist/server/render.js:782:48)
[10:26:58.755] info  - Generating static pages (2/10)
[10:26:58.761] info  - Generating static pages (4/10)
[10:26:58.769] info  - Generating static pages (7/10)
[10:26:58.772] info  - Generating static pages (10/10)
[10:26:58.774] 
[10:26:58.775] > Build error occurred
[10:26:58.777] Error: Export encountered errors on following paths:
[10:26:58.777] 	/posts
[10:26:58.777]     at /vercel/path0/node_modules/next/dist/export/index.js:500:19
[10:26:58.778]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[10:26:58.778]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:20)
[10:26:58.778]     at async /vercel/path0/node_modules/next/dist/build/index.js:1005:17
[10:26:58.778]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:20)
[10:26:58.778]     at async /vercel/path0/node_modules/next/dist/build/index.js:879:13
[10:26:58.778]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:75:20)
[10:26:58.779]     at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:82:25)
[10:26:58.807] error Command failed with exit code 1.
[10:26:58.808] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[10:26:58.832] Error: Command "yarn run build" exited with 1
```

**Comment by brooksdra** [comment]
> @brooksdra Can you write what you are doing for "/posts"? .w.

Thanks for your response; 

The posts directory was there by default, with three files: index.mdx, markdown.mdx, and pages.mdx. 

So, all I did was add another file called example.mdx.

To be clear, my usage of Nextra was prompted by experimenting in Vercel.com, where I started a new site via a Vercel "[Portfolio Starter Kit](https://vercel.com/new/templates/next.js/portfolio-starter-kit)"

My [project](https://clutchstream.com/), currently has nothing much more than the template and a few extra pages.

Thanks again

**Comment by md-weber** [comment]
The nextra-blog is currently not supporting the `meta.json` file. You will have to do it via the frontmatter. 
https://github.com/shuding/nextra/issues/1878#issuecomment-1553536008

**Comment by dimaMachina** [comment]
Supported in Nextra 4 https://the-guild.dev/blog/nextra-4#support-for-_meta-files
