### ISSUE TITLE
Version update 2.7.1 Mermaid not working

### ISSUE THREAD

**Issue by sebiweise** [shuding/nextra#1972]
I´m getting the following error when switching from my own Mermaid integration to the new Mermaid integration in the 2.7.1 version of nextra:

```
ode_modules.pnpm@theguild+remark-mermaid@0.0.1_react@18.2.0
ode_modules@theguild
emark-mermaiddistmermaid.js
Module build failed: UnhandledSchemeError: Reading from "C:*********
ode_modules.pnpm@theguild+remark-mermaid@0.0.1_react@18.2.0
ode_modules@theguild
emark-mermaiddistmermaid.js" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "c:" URIs.
```
OS: Windows
Node: v16.17.1

**Comment by B2o5T** [comment]
I am not using windows, could you debug (in `node_modules` for `@theguild/remark-mermaid` source code) what causing the issue for you?

The plugin code is simple as possible, so I am sure you'll find what cause an issue for you

**Comment by sebiweise** [comment]
I did some testing and on Ubuntu it is working fine. So my CI/CD Pipeline doesn´t have this build error. Just my local env isn´t working. Could be a bug in @theguild/remark-mermaid maybe?!

**Comment by B2o5T** [comment]
I don't know I already wrote you to debug it on windows and not on ubuntu. Also, your error message doesn't contain stacktrace so it doesn't helpful to understand what can be wrong and in which line

**Comment by sebiweise** [comment]
![image](https://github.com/shuding/nextra/assets/22999200/fb0f4590-c217-47cc-9633-3d90beb4ead6)
Thats all I got:
```
> next build

- info Linting and checking validity of types
Failed to compile.

*****
ode_modules.pnpm@theguild+remark-mermaid@0.0.1_react@18.2.0
emark-mermaiddistmermaid.js
Module build failed: UnhandledSchemeError: Reading from "C:ReposDT.DE.Docs
ode_modules.pnpm@theguild+remark-mermaid@0.0.1_react@18.2.0
emark-mermaiddistmermaid.js" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "c:" URIs.
    at C:\*****\node_modules\.pnpm\next@13.4.6_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\webpack\bundle5.js:28:399772
    at Hook.eval [as callAsync] (eval at create (C:\*****\node_modules\.pnpm\next@13.4.6_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\webpack\bundle5.js:13:28867), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\*****\node_modules\.pnpm\next@13.4.6_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\webpack\bundle5.js:13:26021)      
    at Object.processResource (C:\*****\node_modules\.pnpm\next@13.4.6_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\webpack\bundle5.js:28:399697)
    at processResource (C:\*****\node_modules\.pnpm\next@13.4.6_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:5308)
    at iteratePitchingLoaders (C:\*****\node_modules\.pnpm\next@13.4.6_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:4667)
    at runLoaders (C:\*****\node_modules\.pnpm\next@13.4.6_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:8590)
    at NormalModule._doBuild (C:\*****\node_modules\.pnpm\next@13.4.6_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\webpack\bundle5.js:28:399559)
    at NormalModule.build (C:\*****\node_modules\.pnpm\next@13.4.6_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\webpack\bundle5.js:28:401587)
    at C:\*****\node_modules\.pnpm\next@13.4.6_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\webpack\bundle5.js:28:81981

Import trace for requested module:
C:ReposDT.DE.Docs
ode_modules.pnpm@theguild+remark-mermaid@0.0.1_react@18.2.0
emark-mermaiddistmermaid.js
./pages/guide/components/mermaid.mdx


> Build failed because of webpack errors
- info Creating an optimized production build . ELIFECYCLE  Command failed with exit code 1.
```

**Comment by B2o5T** [comment]
try to replace this line https://github.com/the-guild-org/docs/blob/8d1acae06da52c876e92c1457c7e89b3f8ae36ad/packages/remark-mermaid/src/index.ts#L8

with 
```diff
-const COMPONENT_PATH = require.resolve('@theguild/remark-mermaid/mermaid');
+const COMPONENT_PATH = require.resolve('@theguild/remark-mermaid/mermaid').replace(/\\/g, '/');
```

or

```diff
-const COMPONENT_PATH = require.resolve('@theguild/remark-mermaid/mermaid');
+const COMPONENT_PATH = '@theguild/remark-mermaid/mermaid';
```
