### ISSUE TITLE
npm run dev cannot find "dev"

### ISSUE THREAD

**Issue by tony4194** [shuding/nextra#2239]
I am a newbie to Nextra, please point out if there is misbehavior. The environment is Debian. After running "npm run dev" in /nextra/nextra-docs-template, seems like dev cannot be found. The package.json is the same as https://github.com/shuding/nextra-docs-template/blob/main/package.json .

terminal info:
/home/tony/nextra/nextra-docs-template/node_modules/next/dist/cli/next-dev.js:334
            showAll: args["--show-all"] ?? false,
                                         ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.dev (/home/tony/nextra/nextra-docs-template/node_modules/next/dist/lib/commands.js:15:30)
    at Object.<anonymous> (/home/tony/nextra/nextra-docs-template/node_modules/next/dist/bin/next:150:28)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR! code 1
npm ERR! path /home/tony/nextra/nextra-docs-template
npm ERR! command failed
npm ERR! command sh -c next dev

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tony/.npm/_logs/2023-09-03T02_49_24_890Z-debug.log

error log:
20 timing npm:load Completed in 275ms
21 timing command:run-script Completed in 6686ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:314:20)
22 verbose stack     at maybeClose (internal/child_process.js:1022:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
23 verbose pkgid nextra-docs-template@0.0.1
24 verbose cwd /home/tony/nextra/nextra-docs-template
25 verbose Linux 6.1.21-v8+
26 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
27 verbose node v12.22.12
28 verbose npm  v7.5.2
29 error code 1
30 error path /home/tony/nextra/nextra-docs-template
31 error command failed
32 error command sh -c next dev
33 verbose exit 1

**Comment by B2o5T** [comment]
Update your node to 16/18/20, you are using legacy 12

**Comment by tony4194** [comment]
It works! Thanks!
