### ISSUE TITLE
v3 alpha.6: TypeError: Cannot read properties of null (reading 'theme')

### ISSUE THREAD

**Issue by silas** [shuding/nextra#2439]
I get the following error if I don't add a `theme: {}` attribute to every `_meta.ts` item after updating to v3 alpha.6 (from v2).

It's possible I've misconfigured something, but adding the `theme` attribute allows it to start.

```
TypeError: Cannot read properties of null (reading 'theme')
    at extendMeta (webpack-internal:///./node_modules/.pnpm/nextra@3.0.0-alpha.6_next@13.5.4_react-dom@18.2.0_react@18.2.0/node_modules/nextra/dist/client/normalize-pages.js:25:46)
    at normalizePages (webpack-internal:///./node_modules/.pnpm/nextra@3.0.0-alpha.6_next@13.5.4_react-dom@18.2.0_react@18.2.0/node_modules/nextra/dist/client/normalize-pages.js:139:26)
    at eval (webpack-internal:///./node_modules/.pnpm/nextra-theme-docs@3.0.0-alpha.6_next@13.5.4_nextra@3.0.0-alpha.6_react-dom@18.2.0_react@18.2.0/node_modules/nextra-theme-docs/dist/index.js:247:81)
    at Object.useMemo (/tmp/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5124:19)
    at useMemo (/tmp/node_modules/.pnpm/react@18.2.0/node_modules/react/cjs/react.development.js:1650:21)
    at ConfigProvider (webpack-internal:///./node_modules/.pnpm/nextra-theme-docs@3.0.0-alpha.6_next@13.5.4_nextra@3.0.0-alpha.6_react-dom@18.2.0_react@18.2.0/node_modules/nextra-theme-docs/dist/index.js:246:78)
    at renderWithHooks (/tmp/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/tmp/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
    at renderElement (/tmp/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/tmp/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/tmp/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (/tmp/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5920:3)
    at renderElement (/tmp/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6017:11)
    at renderNodeDestructiveImpl (/tmp/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/tmp/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
```

**Comment by silas** [comment]
It looks like it's just if the `_meta` value is `null` (e.g. `export default { index: null }`), which worked in `v2`, but maybe wasn't officially supported even there.

I don't know if this is considered a bug or not, feel free to just close if it.

**Comment by dimaMachina** [comment]
Null is not supported, use empty string
