### ISSUE TITLE
Incompatibility with app router

### ISSUE THREAD

**Issue by ariroseonline** [shuding/nextra#2519]
Nextra fails `npm run dev`. I believe I've isolated it down to the app router being switched on. I've tested against Next 13.5.5, 14.0.0, and 14.0.1.

Steps to reproduce:
1) `npx create-next-app@14.0.0` or `npx create-next-app@latest`
2) Make sure to select App router to `Yes`
3) `npm i nextra nextra-theme-docs`
4) Create `theme.config.jsx` with:
```
export default {
  logo: <span>My Nextra Documentation</span>,
  project: {
    link: "https://github.com/shuding/nextra",
  },
  // ... other theme options
};
```
5) Update `next.config.js` to:

```
const withNextra = require("nextra")({
  theme: "nextra-theme-docs",
  themeConfig: "./theme.config.jsx",
});

module.exports = withNextra();
```
6) `npm run dev` and visit `localhost:3000`

Result:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at readdir (node:fs:1476:10)
    at go$readdir (/Users/*****/******/node_modules/graceful-fs/graceful-fs.js:206:16)
    at readdir (/Users/*****/******/node_modules/graceful-fs/graceful-fs.js:211:12)
    at node:internal/util:375:7
    at new Promise (<anonymous>)
    at readdir (node:internal/util:361:12)
    at /Users/*****/******/node_modules/nextra/dist/index.js:205:25
    at Generator.next (<anonymous>)
    at /Users/*****/******/node_modules/nextra/dist/index.js:58:61
    at new Promise (<anonymous>)
    at __async (/Users/*****/******/node_modules/nextra/dist/index.js:42:10)
    at collectFiles (/Users/*****/******/node_modules/nextra/dist/index.js:197:10)
    at NextraPlugin.<anonymous> (/Users/*****/******/node_modules/nextra/dist/index.js:368:30)
    at Generator.next (<anonymous>)
    at /Users/*****/******/node_modules/nextra/dist/index.js:58:61
    at new Promise (<anonymous>)
    at __async (/Users/*****/******/node_modules/nextra/dist/index.js:42:10)
    at /Users/*****/******/node_modules/nextra/dist/index.js:365:72
    at Hook.eval [as callAsync] (eval at create (/Users/*****/******/node_modules/next/dist/compiled/webpack/bundle5.js:13:28867), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/*****/******/node_modules/next/dist/compiled/webpack/bundle5.js:13:26021)
    at Compiler.compile (/Users/*****/******/node_modules/next/dist/compiled/webpack/bundle5.js:28:148407)
    at /Users/*****/******/node_modules/next/dist/compiled/webpack/bundle5.js:28:489605
    at Hook.eval [as callAsync] (eval at create (/Users/*****/******/node_modules/next/dist/compiled/webpack/bundle5.js:13:28867), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/*****/******/node_modules/next/dist/compiled/webpack/bundle5.js:13:26021)
    at run (/Users/*****/******/node_modules/next/dist/compiled/webpack/bundle5.js:28:488645)
    at /Users/*****/******/node_modules/next/dist/compiled/webpack/bundle5.js:28:488560
    at Compiler.readRecords (/Users/*****/******/node_modules/next/dist/compiled/webpack/bundle5.js:28:146041)
    at run (/Users/*****/******/node_modules/next/dist/compiled/webpack/bundle5.js:28:488493)
    at Watching._go (/Users/*****/******/node_modules/next/dist/compiled/webpack/bundle5.js:28:489629)
    at Watching._invalidate (/Users/*****/******/node_modules/next/dist/compiled/webpack/bundle5.js:28:491912)
    at Watching.invalidate (/Users/*****/******/node_modules/next/dist/compiled/webpack/bundle5.js:28:491706)
    at /Users/*****/******/node_modules/next/dist/compiled/webpack/bundle5.js:28:383455
    at processQueueWorker (/Users/*****/******/node_modules/next/dist/compiled/webpack/bundle5.js:28:382890)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by abenhamdine** [comment]
app router is not currently supported, see https://github.com/shuding/nextra/issues/2023#issuecomment-1613696179

**Comment by ariroseonline** [comment]
@dimaMachina I think it's really worth mentioning this in documentation loud and clear if not already, with the tip to use a side-by-side Pages directory as a workaround. Every new Next project is recommended by Vercel themselves to use the App router, so this creates a bad first impression for the project.

**Comment by abenhamdine** [comment]
> @dimaMachina I think it's really worth mentioning this in documentation loud and clear if not already, with the tip to use a side-by-side Pages directory as a workaround. Every new Next project is recommended by Vercel themselves to use the App router, so this creates a bad first impression for the project.

indeed, I sent a PR : https://github.com/shuding/nextra/pull/2522

**Comment by cruzluna** [comment]
Please update the documentation to clearly state the App router is not supported.

**Comment by apoha-pat** [comment]
Does anyone know if theres a way to embed a nextra app (pages router) within my app router project?
Even if the docs needs to run on a separate server or something, it would be nice to have
