### ISSUE TITLE
Only changed files are built as HTML (Not all files)

### ISSUE THREAD

**Issue by piper-of-dawn** [shuding/nextra#2683]
1. I made the documentation using Nextra which is hosted here
https://www.compare-datasets.kumarshantanu.com/installation

2. The entire menu is first displayed on the Home Page:
![image](https://github.com/shuding/nextra/assets/69080662/f8c94e33-18e9-4182-9231-eba10e201f25)

3. When I click on the "Installation and Quick Start" tab, half of the menu suddenly disappears. I did some hit and trial and discovered that NextJS is only building the pages that changed and persisting the original pages that did not change.
![image](https://github.com/shuding/nextra/assets/69080662/6c0e230d-c8ff-4849-827d-1240f007585c)

**Comment by dimaMachina** [comment]
Can you try Nextra 3 to see if it was fixed? for v2 you can set https://github.com/shuding/nextra/issues/1564#issuecomment-1447419595

**Comment by piper-of-dawn** [comment]
This doesn't work.

```bash
kumar@kumar MINGW64 /c/git/compare_datasets_docs/compare_dataset_docs (main)
$ npm run dev

> compare_datasets_documentation@0.0.1 dev
> next dev

C:\git\compare_datasets_docs\compare_dataset_docs\next.config.js:65
undefined
                           ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\git\compare_datasets_docs\compare_dataset_docs\node_modules\nextra\dist\server\index.js from C:\git\compare_datasets_docs\compare_dataset_docs\next.config.js not supported. 
Instead change the require of index.js in C:\git\compare_datasets_docs\compare_dataset_docs\next.config.js to a dynamic import() which is available in all CommonJS modules.
    at mod.require (C:\git\compare_datasets_docs\compare_dataset_docs\node_modules\next\dist\server\require-hook.js:65:28)
    at Object.<anonymous> (C:\git\compare_datasets_docs\compare_dataset_docs\next.config.js:1:20) {
  code: 'ERR_REQUIRE_ESM'
}
```


Package.json
```json
{
  "name": "compare_datasets_documentation",
  "version": "0.0.1",
  "description": "Official documentation for Compare Datasets",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/shuding/nextra-docs-template.git"
  },
  "author": "Kumar Shantanu",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/shuding/nextra-docs-template/issues"
  },
  "homepage": "https://github.com/shuding/nextra-docs-template#readme",
  "dependencies": {
    "next": "^14.0.0",
    "nextra": "^3.0.0-alpha.22",
    "nextra-theme-blog": "^3.0.0-alpha.22",
    "nextra-theme-docs": "^3.0.0-alpha.22",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "rehype-pretty-code": "^0.12.0"
  },
  "devDependencies": {
    "@types/node": "18.11.10",
    "typescript": "^4.9.3"
  }
}

```
