### ISSUE TITLE
Won´t start in a docker container

### ISSUE THREAD

**Issue by Arcade1080** [shuding/nextra#2868]
Given this docker image: 

`
ARG NODE_VERSION
ARG BUILDER

FROM ${BUILDER} as build

# Set working directory
WORKDIR /usr/src/build

RUN yarn workspace website build
# Prune node_modules
RUN yarn workspaces focus website --production

FROM node:${NODE_VERSION}-alpine as website

ARG NODE_ENV

ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/app

RUN npm install -g pm2@4.5.6

COPY --from=build --chown=node:node /usr/src/build/node_modules ./node_modules
COPY --from=build --chown=node:node /usr/src/build/packages/website/package.json ./
COPY --from=build --chown=node:node /usr/src/build/packages/website/.next ./.next
COPY --from=build --chown=node:node /usr/src/build/packages/website/public ./public
COPY --from=build --chown=node:node /usr/src/build/packages/website/next.config.mjs ./
COPY --from=build --chown=node:node /usr/src/build/packages/website/theme.config.jsx ./
COPY --chown=node:node ./process.yml ./

# image cache folder
RUN mkdir -p .next/cache/images && chown node:node .next/cache/images

# Run container as non-root (unprivileged) user
USER node

# Expose the listening port next
EXPOSE 5002

# Launch app with PM2
CMD [ "pm2-runtime", "/usr/app/process.yml"]`

(process.yml starts nextra w/ "npm run start")

The error message (via docker logs ..) displays:

`⨯ Failed to load next.config.mjs, see more info here https://nextjs.org/docs/messages/next-config-error
Error: > Couldn't find any `pages` or `app` directory. Please create one under the project root
    at findPagesDir (/usr/app/node_modules/next/dist/lib/find-pages-dir.js:42:15)
    at findPagesDirectory (/usr/app/node_modules/nextra/dist/index.js:169:15)
    at Object.<anonymous> (/usr/app/node_modules/nextra/dist/index.js:173:53)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at cjsLoader (node:internal/modules/esm/translators:358:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:307:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)`

Could anyone help me?

**Comment by FranciZhong** [comment]
Hey, does this problem get solved? I got stuck on the same issue. Appreciate it if you can update!

**Comment by syedhammad1** [comment]
Hey, @FranciZhong  use this. by the way I am using bun here, you can replace it with npm. It is working for me.

FROM node:20 AS builder

WORKDIR /app

RUN curl -fsSL https://bun.sh/install | bash

ENV PATH="/root/.bun/bin:${PATH}"

COPY package.json bun.lockb ./

RUN bun install

COPY . .

RUN bun run build

FROM node:20 AS production

WORKDIR /app

RUN curl -fsSL https://bun.sh/install | bash

ENV PATH="/root/.bun/bin:${PATH}"

COPY --from=builder /app/next.config.mjs ./
COPY --from=builder /app/package.json ./
COPY --from=builder /app/bun.lockb ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/pages ./pages 

RUN bun install --production 

EXPOSE 3000

CMD ["bun", "start"]
