### ISSUE TITLE
V3 throw error Module not found: Can't resolve 'module'

### ISSUE THREAD

**Issue by tianyingchun** [shuding/nextra#3410]
▲ Next.js 14.2.15
  - Local:        http://localhost:3000

 ✓ Starting...
   automatically enabled Fast Refresh for 3 custom loaders
 ✓ Ready in 2.7s
 ○ Compiling / ...
 ⨯ ./node_modules/typescript/lib/typescript.js:43171:24
Module not found: Can't resolve 'module'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/twoslash/dist/index.mjs
./node_modules/@shikijs/twoslash/dist/index.mjs
./node_modules/nextra/dist/server/compile.js
./node_modules/nextra/dist/client/components/playground.js
./node_modules/nextra/dist/client/components/index.js
./node_modules/nextra-theme-docs/dist/index.js
./node_modules/next/dist/esm/pages/_app.js
   automatically enabled Fast Refresh for 3 custom loaders
 ⨯ ./node_modules/typescript/lib/typescript.js:43171:24
Module not found: Can't resolve 'module'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/twoslash/dist/index.mjs
./node_modules/@shikijs/twoslash/dist/index.mjs
./node_modules/nextra/dist/server/compile.js
./node_modules/nextra/dist/client/components/playground.js
./node_modules/nextra/dist/client/components/index.js
./node_modules/nextra-theme-docs/dist/index.js
./node_modules/next/dist/esm/pages/_app.js
 ⨯ Error: ENOENT: no such file or directory, open '/Users/tianyingchun/Documents/flatjs-next/biz-doc-android-sweb/.next/fallback-build-manifest.json'
    at readFileSync (node:fs:448:20)
    at loadManifest (/Users/tianyingchun/Documents/flatjs-next/biz-doc-android-sweb/node_modules/next/dist/server/load-manifest.js:36:52)
    at loadManifestWithRetries (/Users/tianyingchun/Documents/flatjs-next/biz-doc-android-sweb/node_modules/next/dist/server/load-components.js:40:51)
    at async loadDefaultErrorComponentsImpl (/Users/tianyingchun/Documents/flatjs-next/biz-doc-android-sweb/node_modules/next/dist/server/load-default-error-components.js:30:24)
    at async DevServer.getFallbackErrorComponents (/Users/tianyingchun/Documents/flatjs-next/biz-doc-android-sweb/node_modules/next/dist/server/dev/next-dev-server.js:594:16)
    at async DevServer.renderErrorToResponseImpl (/Users/tianyingchun/Documents/flatjs-next/biz-doc-android-sweb/node_modules/next/dist/server/base-server.js:2187:40)
    at async DevServer.renderToResponseImpl (/Users/tianyingchun/Documents/flatjs-next/biz-doc-android-sweb/node_modules/next/dist/server/base-server.js:2003:30)
    at async DevServer.pipeImpl (/Users/tianyingchun/Documents/flatjs-next/biz-doc-android-sweb/node_modules/next/dist/server/base-server.js:921:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/tianyingchun/Documents/flatjs-next/biz-doc-android-sweb/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/Users/tianyingchun/Documents/flatjs-next/biz-doc-android-sweb/node_modules/next/dist/server/base-server.js:817:17)
    at async /Users/tianyingchun/Documents/flatjs-next/biz-doc-android-sweb/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/tianyingchun/Documents/flatjs-next/biz-doc-android-sweb/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/tianyingchun/Documents/flatjs-next/biz-doc-android-sweb/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/tianyingchun/Documents/flatjs-next/biz-doc-android-sweb/node_modules/next/dist/server/lib/router-server.js:173:21)
    at async handleRequest (/Users/tianyingchun/Documents/flatjs-next/biz-doc-android-sweb/node_modules/next/dist/server/lib/router-server.js:350:24) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/tianyingchun/Documents/flatjs-next/biz-doc-android-sweb/.next/fallback-build-manifest.json'
}

```
  "next": "^14.2.15",
    "next-runtime-env": "3.2.2",
    "nextra": "3.0.8",
    "nextra-theme-docs": "3.0.8",
```

**Comment by tianyingchun** [comment]
the reproduce repo is here 
https://github.com/tianyingchun/nextra-issue

1. yarn install
2. yarn dev
3.

**Comment by dimaMachina** [comment]
huge thanks for repro! can confirm issue, also it throw only while using `yarn`, but not `pnpm`

**Comment by dimaMachina** [comment]
try https://github.com/shuding/nextra/releases/tag/nextra%403.0.9
