### ISSUE TITLE
Core: Clean build fails as of 6d8656c

### ISSUE THREAD

**Issue by robbear** [shuding/nextra#362]
@shuding I'm finding with the latest change, `2.0.0-alpha.24`, a clean build fails. Ie, if I blow away my site's `.next` directory tree to build fresh, I get the following. Note that turbo may mask this depending on how you force a clean build.
```
raidocs:build: warn  - No ESLint configuration detected. Run next lint to begin setup
raidocs:build: info  - Creating an optimized production build...
raidocs:build: (node:2233317) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/robbear/dev/robbear/rai-ux/raidocs/site/.next/cache/nextra-data-default.json'
raidocs:build:     at Object.openSync (fs.js:476:3)
raidocs:build:     at Object.writeFileSync (fs.js:1467:35)
raidocs:build:     at file:///home/robbear/dev/robbear/rai-ux/raidocs/packages/nextra/dist/loader.mjs:95:8
raidocs:build:     at Generator.next (<anonymous>)
raidocs:build:     at file:///home/robbear/dev/robbear/rai-ux/raidocs/packages/nextra/dist/loader.mjs:37:61
raidocs:build:     at new Promise (<anonymous>)
raidocs:build:     at __async (file:///home/robbear/dev/robbear/rai-ux/raidocs/packages/nextra/dist/loader.mjs:21:10)
raidocs:build:     at addPage (file:///home/robbear/dev/robbear/rai-ux/raidocs/packages/nextra/dist/loader.mjs:78:10)
raidocs:build:     at Object.<anonymous> (file:///home/robbear/dev/robbear/rai-ux/raidocs/packages/nextra/dist/loader.mjs:824:15)
raidocs:build:     at Generator.next (<anonymous>)
raidocs:build: (Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by shuding** [comment]
Thanks for reporting! This was fixed with #370, will do a new release soon.
