### ISSUE TITLE
TypeError: _a.call is not a function

### ISSUE THREAD

**Issue by smakosh** [shuding/nextra#483]
```json
"next": "12.1.0",
"nextra": "^2.0.0-alpha.56",
"nextra-theme-docs": "^2.0.0-alpha.58",
"react": "17.0.1",
"react-dom": "17.0.1"
```

**Comment by shuding** [comment]
The new alpha version requires adding the layout in _app, I think that could be the cause?

**Comment by smakosh** [comment]
Nope here's how my `_app.tsx` looks like

```ts
import "nextra-theme-docs/style.css";
import { OntwikProvider } from "ontwik-ui";

export default function Nextra({ Component, pageProps }) {
  const getLayout = Component.getLayout || ((page) => page);
  return getLayout(
    <OntwikProvider>
      <>
        <Component {...pageProps} />
      </>
    </OntwikProvider>
  );
}
```

**Comment by B2o5T** [comment]
Hi @smakosh, Do you still have this problem?

**Comment by smakosh** [comment]
Yes

**Comment by B2o5T** [comment]
@smakosh Did you tried latest beta version? Also did you tried comment OntwikProvider?

**Comment by smakosh** [comment]
Yup

**Comment by smakosh** [comment]
I have invited to the repo and you see [here](https://github.com/smakosh/ontwik-ui-2/blob/main/apps/public-docs/package.json#L14) that I'm using the latest beta

**Comment by B2o5T** [comment]
@smakosh thanks for invite!
So i got the same error
```
error - TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (/Users/dimitri/Desktop/ontwik-ui-2/node_modules/react/cjs/react.development.js:1616:21)
    at exports.ThemeProvider (/Users/dimitri/Desktop/ontwik-ui-2/node_modules/styled-components/dist/styled-components.cjs.js:1:24917)
    at processChild (/Users/dimitri/Desktop/ontwik-ui-2/apps/public-docs/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/dimitri/Desktop/ontwik-ui-2/apps/public-docs/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/dimitri/Desktop/ontwik-ui-2/apps/public-docs/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/dimitri/Desktop/ontwik-ui-2/apps/public-docs/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (/Users/dimitri/Desktop/ontwik-ui-2/apps/public-docs/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/Users/dimitri/Desktop/ontwik-ui-2/apps/public-docs/node_modules/next/dist/server/render.js:756:46)
    at Object.defaultGetInitialProps (/Users/dimitri/Desktop/ontwik-ui-2/apps/public-docs/node_modules/next/dist/server/render.js:369:51)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:21:20) {
  page: '/'
}
```

If you take a look at stacktrace error goes from `styled-components`:
```
    at exports.ThemeProvider (/Users/dimitri/Desktop/ontwik-ui-2/node_modules/styled-components/dist/styled-components.cjs.js:1:24917)
```
removing `OntwikProvider` fixes your issue
```jsx
import "nextra-theme-docs/style.css";

export default function Nextra({ Component, pageProps }) {
  const getLayout = Component.getLayout || ((page) => page);
  return getLayout(<Component {...pageProps} />);
}
```

**Comment by smakosh** [comment]
Interesting, closing the issue as it's unrelated

**Comment by smakosh** [comment]
Re-oppenning:

```bash
error - node_modules/nextra-theme-docs/dist/index.js (1428:3) @ Head
public-docs:dev: error - TypeError: _a.call is not a function
public-docs:dev:     at Head (webpack-internal:///./node_modules/nextra-theme-docs/dist/index.js:1463:48)
public-docs:dev:     at processChild (/Users/smakosh/Desktop/open-source/libraries/ontwik-ui-2/apps/public-docs/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
public-docs:dev:     at resolve (/Users/smakosh/Desktop/open-source/libraries/ontwik-ui-2/apps/public-docs/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
public-docs:dev:     at ReactDOMServerRenderer.render (/Users/smakosh/Desktop/open-source/libraries/ontwik-ui-2/apps/public-docs/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
public-docs:dev:     at ReactDOMServerRenderer.read (/Users/smakosh/Desktop/open-source/libraries/ontwik-ui-2/apps/public-docs/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
public-docs:dev:     at Object.renderToString (/Users/smakosh/Desktop/open-source/libraries/ontwik-ui-2/apps/public-docs/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
public-docs:dev:     at Object.renderPage (/Users/smakosh/Desktop/open-source/libraries/ontwik-ui-2/apps/public-docs/node_modules/next/dist/server/render.js:662:46)
public-docs:dev:     at Object.defaultGetInitialProps (/Users/smakosh/Desktop/open-source/libraries/ontwik-ui-2/apps/public-docs/node_modules/next/dist/server/render.js:332:67)
public-docs:dev:     at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:21:20)
public-docs:dev:     at Object.<anonymous> (/Users/smakosh/Desktop/open-source/libraries/ontwik-ui-2/apps/public-docs/node_modules/next/dist/shared/lib/utils.js:75:33) {
public-docs:dev:   page: '/'
public-docs:dev: }
public-docs:dev: null
```

@B2o5T see: https://github.com/smakosh/ontwik-ui-2/pull/1

**Comment by smakosh** [comment]
Duplicate of https://github.com/shuding/nextra/issues/716
