### ISSUE TITLE
error - SyntaxError: Invalid regular expression: /\bC++\b/: Nothing to repeat

### ISSUE THREAD

**Issue by SincerelyFaust** [shuding/nextra#667]
I get this error straight after running `pnpm dev`.
nextra version: `2.0.0-beta.16`
nextra-theme-docs version: `2.0.0-beta.16`

```sh
error - SyntaxError: Invalid regular expression: /\bC++\b/: Nothing to repeat
    at new RegExp (<anonymous>)
    at eval (webpack-internal:///./node_modules/.pnpm/title@3.5.0/node_modules/title/lib/index.js:8:56)
    at Array.map (<anonymous>)
    at convertToRegExp (webpack-internal:///./node_modules/.pnpm/title@3.5.0/node_modules/title/lib/index.js:8:46)
    at module.exports (webpack-internal:///./node_modules/.pnpm/title@3.5.0/node_modules/title/lib/index.js:47:25)
    at normalizePages (webpack-internal:///./node_modules/.pnpm/nextra-theme-docs@2.0.0-beta.16_vyccxgqxcnj5vudpssiumaxlme/node_modules/nextra-theme-docs/dist/index.js:2125:119)
    at normalizePages (webpack-internal:///./node_modules/.pnpm/nextra-theme-docs@2.0.0-beta.16_vyccxgqxcnj5vudpssiumaxlme/node_modules/nextra-theme-docs/dist/index.js:2129:45)
    at eval (webpack-internal:///./node_modules/.pnpm/nextra-theme-docs@2.0.0-beta.16_vyccxgqxcnj5vudpssiumaxlme/node_modules/nextra-theme-docs/dist/index.js:2274:12)
    at Object.useMemo (/Users/faust/Desktop/Dev/Repos/dahliaOS/documentation/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5124:19)
    at useMemo (/Users/faust/Desktop/Dev/Repos/dahliaOS/documentation/node_modules/.pnpm/react@18.2.0/node_modules/react/cjs/react.development.js:1650:21) {
  page: '/'
}
```
`index.mdx`
```ts
import Callout from "nextra-theme-docs";

# Welcome to the dahliaOS documentation

<Callout type="warning" emoji="⚠️">
  dahliaOS is currently in the alpha phase of development meaning most
  applications it ships with are unfinished, some features are missing and it is
  not stable nor daily drivable.
</Callout>

dahliaOS is a modern, secure, lightweight and responsive operating system, combining the best of GNU/Linux and Fuchsia OS.
We are developing a privacy-respecting, fast, secure and lightweight operating system, our goal is to offer our users an incredible experience to help with their daily tasks.
```

**Comment by B2o5T** [comment]
Use named import `import { Callout } from "nextra-theme-docs";`

**Comment by SincerelyFaust** [comment]
Just did and I get the same error again

**Comment by EpicEmeraldPlayz** [comment]
I think this have to deal with `title` package (https://github.com/vercel/title)

**Comment by shuding** [comment]
Seems like a bug in `title` indeed: https://runkit.com/embed/a4v7qa0uvbmi

<img width="790" alt="CleanShot 2022-08-09 at 20 24 34@2x" src="https://user-images.githubusercontent.com/3676859/183733554-0f9ccf24-7f93-48f1-8313-fa9a59cd883f.png">
