### ISSUE TITLE
TypeError: _a.call is not a function

### ISSUE THREAD

**Issue by chilikasha** [shuding/nextra#716]
Hi,
Updated to beta 18 and getting this error when opening the project locally (works fine on beta 17)
```
event - compiled client and server successfully in 151 ms (329 modules)
error - node_modules/nextra-theme-docs/dist/index.js (1428:3) @ Head
error - TypeError: _a.call is not a function

    at Head (webpack-internal:///./node_modules/nextra-theme-docs/dist/index.js:1463:48)
    at renderWithHooks (/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/node_modules/react-dom/cjs/react-dom-server.browser.development.js:57
31:15)
    at renderElement (/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:
11)
    at renderNodeDestructive (/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:
7)
    at renderNodeDestructive (/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
{
  page: '/'
}
null
```

**Comment by B2o5T** [comment]
it seems like your theme config property `head` is not a function?
